//
// This source file is part of the Stanford Spezi open source project
//
// SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/~__root'
import { Route as dashboardLayoutRouteImport } from './routes/~(dashboard)/~layout'
import { Route as dashboardOnboardingRouteImport } from './routes/~(dashboard)/~onboarding'
import { Route as authSignInRouteImport } from './routes/~(auth)/~sign-in'
import { Route as dashboardIndexRouteImport } from './routes/~(dashboard)/~index'
import { Route as dashboardGroupStudyLayoutRouteImport } from './routes/~(dashboard)/~$group/~$study/~layout'
import { Route as dashboardGroupIndexRouteImport } from './routes/~(dashboard)/~$group/~index'
import { Route as dashboardGroupStudyIndexRouteImport } from './routes/~(dashboard)/~$group/~$study/~index'
import { Route as dashboardGroupStudyConfigurationParticipationRouteImport } from './routes/~(dashboard)/~$group/~$study/~configuration/~participation'
import { Route as dashboardGroupStudyConfigurationGeneralRouteImport } from './routes/~(dashboard)/~$group/~$study/~configuration/~general'
import { Route as dashboardGroupStudyConfigurationIndexRouteImport } from './routes/~(dashboard)/~$group/~$study/~configuration/~index'
import { Route as dashboardGroupStudyConfigurationComponentsIndexRouteImport } from './routes/~(dashboard)/~$group/~$study/~configuration/~components/~index'
import { Route as dashboardGroupStudyConfigurationComponentsComponentTypeNewRouteImport } from './routes/~(dashboard)/~$group/~$study/~configuration/~components/~$componentType/~new'
import { Route as dashboardGroupStudyConfigurationComponentsComponentTypeComponentRouteImport } from './routes/~(dashboard)/~$group/~$study/~configuration/~components/~$componentType/~$component'

const dashboardLayoutRoute = dashboardLayoutRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardOnboardingRoute = dashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const dashboardGroupStudyLayoutRoute =
  dashboardGroupStudyLayoutRouteImport.update({
    id: '/$group/$study',
    path: '/$group/$study',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)
const dashboardGroupIndexRoute = dashboardGroupIndexRouteImport.update({
  id: '/$group/',
  path: '/$group/',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const dashboardGroupStudyIndexRoute =
  dashboardGroupStudyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardGroupStudyLayoutRoute,
  } as any)
const dashboardGroupStudyConfigurationParticipationRoute =
  dashboardGroupStudyConfigurationParticipationRouteImport.update({
    id: '/configuration/participation',
    path: '/configuration/participation',
    getParentRoute: () => dashboardGroupStudyLayoutRoute,
  } as any)
const dashboardGroupStudyConfigurationGeneralRoute =
  dashboardGroupStudyConfigurationGeneralRouteImport.update({
    id: '/configuration/general',
    path: '/configuration/general',
    getParentRoute: () => dashboardGroupStudyLayoutRoute,
  } as any)
const dashboardGroupStudyConfigurationIndexRoute =
  dashboardGroupStudyConfigurationIndexRouteImport.update({
    id: '/configuration/',
    path: '/configuration/',
    getParentRoute: () => dashboardGroupStudyLayoutRoute,
  } as any)
const dashboardGroupStudyConfigurationComponentsIndexRoute =
  dashboardGroupStudyConfigurationComponentsIndexRouteImport.update({
    id: '/configuration/components/',
    path: '/configuration/components/',
    getParentRoute: () => dashboardGroupStudyLayoutRoute,
  } as any)
const dashboardGroupStudyConfigurationComponentsComponentTypeNewRoute =
  dashboardGroupStudyConfigurationComponentsComponentTypeNewRouteImport.update({
    id: '/configuration/components/$componentType/new',
    path: '/configuration/components/$componentType/new',
    getParentRoute: () => dashboardGroupStudyLayoutRoute,
  } as any)
const dashboardGroupStudyConfigurationComponentsComponentTypeComponentRoute =
  dashboardGroupStudyConfigurationComponentsComponentTypeComponentRouteImport.update(
    {
      id: '/configuration/components/$componentType/$component',
      path: '/configuration/components/$componentType/$component',
      getParentRoute: () => dashboardGroupStudyLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof dashboardIndexRoute
  '/sign-in': typeof authSignInRoute
  '/onboarding': typeof dashboardOnboardingRoute
  '/$group/': typeof dashboardGroupIndexRoute
  '/$group/$study': typeof dashboardGroupStudyLayoutRouteWithChildren
  '/$group/$study/': typeof dashboardGroupStudyIndexRoute
  '/$group/$study/configuration/': typeof dashboardGroupStudyConfigurationIndexRoute
  '/$group/$study/configuration/general': typeof dashboardGroupStudyConfigurationGeneralRoute
  '/$group/$study/configuration/participation': typeof dashboardGroupStudyConfigurationParticipationRoute
  '/$group/$study/configuration/components/': typeof dashboardGroupStudyConfigurationComponentsIndexRoute
  '/$group/$study/configuration/components/$componentType/$component': typeof dashboardGroupStudyConfigurationComponentsComponentTypeComponentRoute
  '/$group/$study/configuration/components/$componentType/new': typeof dashboardGroupStudyConfigurationComponentsComponentTypeNewRoute
}
export interface FileRoutesByTo {
  '/': typeof dashboardIndexRoute
  '/sign-in': typeof authSignInRoute
  '/onboarding': typeof dashboardOnboardingRoute
  '/$group': typeof dashboardGroupIndexRoute
  '/$group/$study': typeof dashboardGroupStudyIndexRoute
  '/$group/$study/configuration': typeof dashboardGroupStudyConfigurationIndexRoute
  '/$group/$study/configuration/general': typeof dashboardGroupStudyConfigurationGeneralRoute
  '/$group/$study/configuration/participation': typeof dashboardGroupStudyConfigurationParticipationRoute
  '/$group/$study/configuration/components': typeof dashboardGroupStudyConfigurationComponentsIndexRoute
  '/$group/$study/configuration/components/$componentType/$component': typeof dashboardGroupStudyConfigurationComponentsComponentTypeComponentRoute
  '/$group/$study/configuration/components/$componentType/new': typeof dashboardGroupStudyConfigurationComponentsComponentTypeNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)': typeof dashboardLayoutRouteWithChildren
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(dashboard)/onboarding': typeof dashboardOnboardingRoute
  '/(dashboard)/$group/': typeof dashboardGroupIndexRoute
  '/(dashboard)/$group/$study': typeof dashboardGroupStudyLayoutRouteWithChildren
  '/(dashboard)/$group/$study/': typeof dashboardGroupStudyIndexRoute
  '/(dashboard)/$group/$study/configuration/': typeof dashboardGroupStudyConfigurationIndexRoute
  '/(dashboard)/$group/$study/configuration/general': typeof dashboardGroupStudyConfigurationGeneralRoute
  '/(dashboard)/$group/$study/configuration/participation': typeof dashboardGroupStudyConfigurationParticipationRoute
  '/(dashboard)/$group/$study/configuration/components/': typeof dashboardGroupStudyConfigurationComponentsIndexRoute
  '/(dashboard)/$group/$study/configuration/components/$componentType/$component': typeof dashboardGroupStudyConfigurationComponentsComponentTypeComponentRoute
  '/(dashboard)/$group/$study/configuration/components/$componentType/new': typeof dashboardGroupStudyConfigurationComponentsComponentTypeNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/onboarding'
    | '/$group/'
    | '/$group/$study'
    | '/$group/$study/'
    | '/$group/$study/configuration/'
    | '/$group/$study/configuration/general'
    | '/$group/$study/configuration/participation'
    | '/$group/$study/configuration/components/'
    | '/$group/$study/configuration/components/$componentType/$component'
    | '/$group/$study/configuration/components/$componentType/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/onboarding'
    | '/$group'
    | '/$group/$study'
    | '/$group/$study/configuration'
    | '/$group/$study/configuration/general'
    | '/$group/$study/configuration/participation'
    | '/$group/$study/configuration/components'
    | '/$group/$study/configuration/components/$componentType/$component'
    | '/$group/$study/configuration/components/$componentType/new'
  id:
    | '__root__'
    | '/(dashboard)'
    | '/(dashboard)/'
    | '/(auth)/sign-in'
    | '/(dashboard)/onboarding'
    | '/(dashboard)/$group/'
    | '/(dashboard)/$group/$study'
    | '/(dashboard)/$group/$study/'
    | '/(dashboard)/$group/$study/configuration/'
    | '/(dashboard)/$group/$study/configuration/general'
    | '/(dashboard)/$group/$study/configuration/participation'
    | '/(dashboard)/$group/$study/configuration/components/'
    | '/(dashboard)/$group/$study/configuration/components/$componentType/$component'
    | '/(dashboard)/$group/$study/configuration/components/$componentType/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardLayoutRoute: typeof dashboardLayoutRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/onboarding': {
      id: '/(dashboard)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof dashboardOnboardingRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/$group/$study': {
      id: '/(dashboard)/$group/$study'
      path: '/$group/$study'
      fullPath: '/$group/$study'
      preLoaderRoute: typeof dashboardGroupStudyLayoutRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/$group/': {
      id: '/(dashboard)/$group/'
      path: '/$group'
      fullPath: '/$group/'
      preLoaderRoute: typeof dashboardGroupIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/$group/$study/': {
      id: '/(dashboard)/$group/$study/'
      path: '/'
      fullPath: '/$group/$study/'
      preLoaderRoute: typeof dashboardGroupStudyIndexRouteImport
      parentRoute: typeof dashboardGroupStudyLayoutRoute
    }
    '/(dashboard)/$group/$study/configuration/participation': {
      id: '/(dashboard)/$group/$study/configuration/participation'
      path: '/configuration/participation'
      fullPath: '/$group/$study/configuration/participation'
      preLoaderRoute: typeof dashboardGroupStudyConfigurationParticipationRouteImport
      parentRoute: typeof dashboardGroupStudyLayoutRoute
    }
    '/(dashboard)/$group/$study/configuration/general': {
      id: '/(dashboard)/$group/$study/configuration/general'
      path: '/configuration/general'
      fullPath: '/$group/$study/configuration/general'
      preLoaderRoute: typeof dashboardGroupStudyConfigurationGeneralRouteImport
      parentRoute: typeof dashboardGroupStudyLayoutRoute
    }
    '/(dashboard)/$group/$study/configuration/': {
      id: '/(dashboard)/$group/$study/configuration/'
      path: '/configuration'
      fullPath: '/$group/$study/configuration/'
      preLoaderRoute: typeof dashboardGroupStudyConfigurationIndexRouteImport
      parentRoute: typeof dashboardGroupStudyLayoutRoute
    }
    '/(dashboard)/$group/$study/configuration/components/': {
      id: '/(dashboard)/$group/$study/configuration/components/'
      path: '/configuration/components'
      fullPath: '/$group/$study/configuration/components/'
      preLoaderRoute: typeof dashboardGroupStudyConfigurationComponentsIndexRouteImport
      parentRoute: typeof dashboardGroupStudyLayoutRoute
    }
    '/(dashboard)/$group/$study/configuration/components/$componentType/new': {
      id: '/(dashboard)/$group/$study/configuration/components/$componentType/new'
      path: '/configuration/components/$componentType/new'
      fullPath: '/$group/$study/configuration/components/$componentType/new'
      preLoaderRoute: typeof dashboardGroupStudyConfigurationComponentsComponentTypeNewRouteImport
      parentRoute: typeof dashboardGroupStudyLayoutRoute
    }
    '/(dashboard)/$group/$study/configuration/components/$componentType/$component': {
      id: '/(dashboard)/$group/$study/configuration/components/$componentType/$component'
      path: '/configuration/components/$componentType/$component'
      fullPath: '/$group/$study/configuration/components/$componentType/$component'
      preLoaderRoute: typeof dashboardGroupStudyConfigurationComponentsComponentTypeComponentRouteImport
      parentRoute: typeof dashboardGroupStudyLayoutRoute
    }
  }
}

interface dashboardGroupStudyLayoutRouteChildren {
  dashboardGroupStudyIndexRoute: typeof dashboardGroupStudyIndexRoute
  dashboardGroupStudyConfigurationIndexRoute: typeof dashboardGroupStudyConfigurationIndexRoute
  dashboardGroupStudyConfigurationGeneralRoute: typeof dashboardGroupStudyConfigurationGeneralRoute
  dashboardGroupStudyConfigurationParticipationRoute: typeof dashboardGroupStudyConfigurationParticipationRoute
  dashboardGroupStudyConfigurationComponentsIndexRoute: typeof dashboardGroupStudyConfigurationComponentsIndexRoute
  dashboardGroupStudyConfigurationComponentsComponentTypeComponentRoute: typeof dashboardGroupStudyConfigurationComponentsComponentTypeComponentRoute
  dashboardGroupStudyConfigurationComponentsComponentTypeNewRoute: typeof dashboardGroupStudyConfigurationComponentsComponentTypeNewRoute
}

const dashboardGroupStudyLayoutRouteChildren: dashboardGroupStudyLayoutRouteChildren =
  {
    dashboardGroupStudyIndexRoute: dashboardGroupStudyIndexRoute,
    dashboardGroupStudyConfigurationIndexRoute:
      dashboardGroupStudyConfigurationIndexRoute,
    dashboardGroupStudyConfigurationGeneralRoute:
      dashboardGroupStudyConfigurationGeneralRoute,
    dashboardGroupStudyConfigurationParticipationRoute:
      dashboardGroupStudyConfigurationParticipationRoute,
    dashboardGroupStudyConfigurationComponentsIndexRoute:
      dashboardGroupStudyConfigurationComponentsIndexRoute,
    dashboardGroupStudyConfigurationComponentsComponentTypeComponentRoute:
      dashboardGroupStudyConfigurationComponentsComponentTypeComponentRoute,
    dashboardGroupStudyConfigurationComponentsComponentTypeNewRoute:
      dashboardGroupStudyConfigurationComponentsComponentTypeNewRoute,
  }

const dashboardGroupStudyLayoutRouteWithChildren =
  dashboardGroupStudyLayoutRoute._addFileChildren(
    dashboardGroupStudyLayoutRouteChildren,
  )

interface dashboardLayoutRouteChildren {
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardOnboardingRoute: typeof dashboardOnboardingRoute
  dashboardGroupIndexRoute: typeof dashboardGroupIndexRoute
  dashboardGroupStudyLayoutRoute: typeof dashboardGroupStudyLayoutRouteWithChildren
}

const dashboardLayoutRouteChildren: dashboardLayoutRouteChildren = {
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardOnboardingRoute: dashboardOnboardingRoute,
  dashboardGroupIndexRoute: dashboardGroupIndexRoute,
  dashboardGroupStudyLayoutRoute: dashboardGroupStudyLayoutRouteWithChildren,
}

const dashboardLayoutRouteWithChildren = dashboardLayoutRoute._addFileChildren(
  dashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardLayoutRoute: dashboardLayoutRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
